=== uo288285/sew/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uniovi.es" xmlns="http://www.uniovi.es" elementFormDefault="qualified">    
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidadProxima" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="galeriaFoto" />
				<xs:element ref="galeriaVideo" />
				<xs:element ref="origen" />
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="puntosAnonimos" />
				<xs:element ref="ganador" />
				<xs:element ref="tiempoGanador" />
				<xs:element ref="clasificación" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaFoto">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="galeriaVideo">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="origen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntosAnonimos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tramo" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudC" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificación">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:integer">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="vueltas" type="xs:integer" />
	<xs:element name="localidadProxima" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="foto">
		<xs:complexType>
			<xs:attribute name="fuente" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:attribute name="fuente" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="ganador" type="xs:string" />
	<xs:element name="tiempoGanador" type="xs:duration" />
	<xs:element name="piloto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="puesto" type="xs:integer" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudC">
		<xs:simpleType>
			<xs:restriction base= "xs:double">
				<xs:minInclusive value="-180"></xs:minInclusive>
				<xs:maxInclusive value="180"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="latitud">
		<xs:simpleType>
			<xs:restriction base= "xs:double">
				<xs:minInclusive value="-90"></xs:minInclusive>
				<xs:maxInclusive value="90"></xs:maxInclusive>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base= "AltitudType">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>


<xs:simpleType name ="AltitudType">
	<xs:restriction base="xs:double">
		<xs:minInclusive value="0"></xs:minInclusive>
		<xs:maxInclusive value="5000"></xs:maxInclusive>
	</xs:restriction>
</xs:simpleType>

	<xs:element name="tramo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:double">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:integer" />
</xs:schema>

=== uo288285/sew/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
<nombre>Petronas Sepang International Circuit</nombre>
<longitud unidades="metros"> 5543</longitud>
    <anchura unidades= "metros"> 25 </anchura>
    <fecha>2025-10-26</fecha>
    <hora>08:00:00</hora>
    <vueltas>21</vueltas>
    <localidadProxima>Sepang</localidadProxima>
    <pais>Malasia</pais>
    <patrocinador>Petronas</patrocinador>
    <referencias>
    <referencia> https://www.autobild.es/reportajes/asi-es-circuito-sepang-270281</referencia>
    <referencia>https://www.estadiodeportivo.com/motor/motogp/circuito-internacional-sepang-longitud-curvas-vuelta-record-del-trazado-del-malasia-motogp-20250315-486503.html</referencia>
    <referencia>https://www.sepangcircuit.com/</referencia>
    </referencias>
    
    <galeriaFoto>
        <foto fuente="sepang1.jpg" />
        <foto fuente="sepang2.jpg" />
        <foto fuente="sepang3.jpg" />
    </galeriaFoto>
    <galeriaVideo>
        <video fuente="videoSepang.mp4" />
    </galeriaVideo>
    <origen>
        <coordenadas>
            <longitudC> 101.73833 </longitudC>
            <latitud> 2.76056 </latitud>
            <altitud unidades="metros "> 35.76</altitud>
        </coordenadas>
    </origen>
    <puntosAnonimos>
        <tramo unidades="metros">640</tramo>
        <coordenadas>
            <longitudC> 101.73250 </longitudC>
            <latitud> 2.76056 </latitud>
            <altitud unidades="metros">37.46</altitud>  
        </coordenadas>
        <sector>1</sector>
    </puntosAnonimos>
    <puntosAnonimos>
        <tramo unidades="metros">105</tramo>
        <coordenadas>
            <longitudC> 101.73333 </longitudC>
            <latitud> 2.76083 </latitud>
            <altitud unidades="metros">35.05</altitud>  
        </coordenadas>
        <sector>1</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">255</tramo>
        <coordenadas>
            <longitudC>101.733056</longitudC>
            <latitud>2.763056</latitud>
            <altitud unidades="metros">23.2</altitud>  
        </coordenadas>
        <sector>1</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">520</tramo>
        <coordenadas>
            <longitudC>101.7375</longitudC>
            <latitud>2.765</latitud>
            <altitud unidades="metros">36.98</altitud>  
        </coordenadas>
        <sector>2</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">330</tramo>
        <coordenadas>
            <longitudC>101.738611</longitudC>
            <latitud>2.762222</latitud>
            <altitud unidades="metros">36.65</altitud>  
        </coordenadas>
        <sector>2</sector>
    </puntosAnonimos>

    
    <puntosAnonimos>
        <tramo unidades="metros">244</tramo>
        <coordenadas>
            <longitudC>101.740555</longitudC>
            <latitud>2.762778</latitud>
            <altitud unidades="metros">38.66</altitud>  
        </coordenadas>
        <sector>2</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">360</tramo>
        <coordenadas>
            <longitudC>101.742777</longitudC>
            <latitud>2.760556</latitud>
            <altitud unidades="metros">38.77</altitud>  
        </coordenadas>
        <sector>2</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">114</tramo>
        <coordenadas>
            <longitudC>101.7425</longitudC>
            <latitud>2.759444</latitud>
            <altitud unidades="metros">38.11</altitud>  
        </coordenadas>
        <sector>2</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">485</tramo>
        <coordenadas>
            <longitudC>101.738333</longitudC>
            <latitud>2.759167</latitud>
            <altitud unidades="metros">34.17</altitud>  
        </coordenadas>
        <sector>2</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">140</tramo>
        <coordenadas>
            <longitudC>101.739166</longitudC>
            <latitud>2.758333</latitud>
            <altitud unidades="metros">41.1</altitud>  
        </coordenadas>
        <sector>3</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">202</tramo>
        <coordenadas>
            <longitudC>101.738611</longitudC>
            <latitud>2.756389</latitud>
            <altitud unidades="metros">44.07</altitud>  
        </coordenadas>
        <sector>3</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">330</tramo>
        <coordenadas>
            <longitudC>101.736111</longitudC>
        <latitud>2.758056</latitud>
            <altitud unidades="metros">36.23</altitud>  
        </coordenadas>
        <sector>3</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">195</tramo>
        <coordenadas>
            <longitudC>101.734444</longitudC>
            <latitud>2.757778</latitud>
            <altitud unidades="metros">32.35</altitud>  
        </coordenadas>
        <sector>3</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">150</tramo>
        <coordenadas>
            <longitudC>101.733611</longitudC>
            <latitud>2.758611</latitud>
            <altitud unidades="metros">36.16</altitud>  
        </coordenadas>
        <sector>3</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">905</tramo>
        <coordenadas>
            <longitudC>101.741389</longitudC>
            <latitud>2.760556</latitud>
            <altitud unidades="metros">37.65</altitud>  
        </coordenadas>
        <sector>3</sector>
    </puntosAnonimos>

    <puntosAnonimos>
        <tramo unidades="metros">358</tramo>
        <coordenadas>
            <longitudC>101.738333</longitudC>
            <latitud>2.760556</latitud>
            <altitud unidades="metros">35.67</altitud>  
        </coordenadas>
        <sector>3</sector>
    </puntosAnonimos>

    <ganador>Alex Márquez</ganador>
    <tiempoGanador> PT40M9S</tiempoGanador>

    <clasificación>
    <piloto puesto= "1">Marc Márquez</piloto>
    <piloto puesto="2">Alex Márquez</piloto>
    <piloto puesto="3">Marco Bezzechi</piloto>
    </clasificación>
</circuito>
